model_name_or_path: /wekafs/ict/hx_624/models/Qwen3.5-9B
trust_remote_code: true
flash_attn: fa2
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: true
dataset_dir: /wekafs/ict/hx_624/llm-ft/data/lf
dataset: md_openscad_train
eval_dataset: md_openscad_val
template: qwen3_5
enable_thinking: false
cutoff_len: 8192
preprocessing_num_workers: 16
dataloader_num_workers: 4
neat_packing: true
packing: true
tokenized_path: /wekafs/ict/hx_624/llm-ft/data/lf/tokenized_md_openscad_len8192_packed
output_dir: /wekafs/ict/hx_624/llm-ft/runs/lf_qwen35_9b_lora_md_openscad
logging_steps: 5
save_steps: 50
save_only_model: true
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
save_total_limit: 2
