model_name_or_path: /wekafs/ict/hx_624/models/Qwen3.8-27B
trust_remote_code: true
flash_attn: fa2
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: true
dataset_dir: /wekafs/ict/hx_624/llm-ft/data/lf
dataset: md_27b_v3_train
eval_dataset: md_27b_v3_val
template: qwen3_5
enable_thinking: false
cutoff_len: 3072
preprocessing_num_workers: 16
dataloader_num_workers: 4
neat_packing: true
packing: true
tokenized_path: /wekafs/ict/hx_624/llm-ft/data/lf/tokenized_md_27b_v3_len3072_packed
output_dir: /wekafs/ict/hx_624/llm-ft/runs/lf_qwen38_27b_lora_v3
logging_steps: 5
save_steps: 250
save_only_model: true
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
per_device_train_batch_size: 1
gradient_accumulation_steps: 6
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250
save_total_limit: 8
