model_name_or_path: /wekafs/ict/hx_624/models/Qwen3.5-9B
trust_remote_code: true
flash_attn: fa2
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: true
dataset_dir: /wekafs/ict/hx_624/llm-ft/data/img_code
dataset: img_code_train
eval_dataset: img_code_val
template: qwen3_5
enable_thinking: false
cutoff_len: 8192
preprocessing_num_workers: 16
dataloader_num_workers: 4
neat_packing: false
packing: false
tokenized_path: /wekafs/ict/hx_624/llm-ft/data/lf/tok_img_code
output_dir: /wekafs/ict/hx_624/llm-ft/runs/lf_qwen35_9b_img
logging_steps: 5
save_steps: 200
save_only_model: true
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
save_total_limit: 4
