"""Deterministic scene assembler for the scene track's parallel mode.

Zone agents write ``src/zones/<snake>.js`` (``build(ctx) → Group``) and an env
agent writes ``src/env.js``; this module (code, not an LLM) then:

1. probes every zone module in the browser host (``probe_zone_modules``),
   passing the sun azimuth (``SUN_AZIMUTH_DEG`` from env.js): does it import,
   does ``build(ctx)`` return an Object3D, what is its bbox — and the driver
   (``probe_scene.mjs --sun-azimuth``, camera math owned by
   ``runtime_js/lib/orbit.mjs``) fits overview + per-zone cameras, eye on the
   sun side, from the measured bboxes;
2. converts those fitted specs into ``CameraPlan``s (``cameras_from_specs``;
   the only camera math left in python is the no-measurable-zones fallback);
3. writes ``src/scene.js`` importing only the healthy zones, naming groups,
   preloading ``public/assets/*.glb`` into ``ctx.assets`` and fanning
   ``update(t, dt)`` out to env + zones (``assemble``).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from codeverse.contracts.plan import CameraPlan, ScenePlan
from codeverse.conventions import to_pascal, to_snake
from codeverse.workspace import Workspace

PROBE_REL = "src/_c3v_assemble_probe.js"
_PREFIX = "[3dcv-assemble]"
_SUN_RE = re.compile(r"export\s+const\s+SUN_AZIMUTH_DEG\s*=\s*(-?\d+(?:\.\d+)?)")


class ZoneProbe(BaseModel):
    name: str
    file: str
    ok: bool
    error: str = ""
    bbox: dict[str, Any] | None = None
    meshes: int = 0
    triangles: int = 0


class ZoneProbeReport(BaseModel):
    """``probe_zone_modules`` outcome.  Unpacks as ``probes, census, other = ...``
    (historical 3-tuple); ``camera_specs`` carries the driver-fitted cameras
    (``{azimuth, overview, zones:[{group, position, lookAt, fov}]}``)."""

    probes: dict[str, ZoneProbe] = Field(default_factory=dict)
    census: dict[str, Any] = Field(default_factory=dict)
    other_errors: list[str] = Field(default_factory=list)
    camera_specs: dict[str, Any] = Field(default_factory=dict)

    def __iter__(self):  # type: ignore[override]
        yield self.probes
        yield self.census
        yield self.other_errors


class AssembleResult(BaseModel):
    scene_path: str
    zones_included: list[str] = Field(default_factory=list)
    zones_failed: dict[str, str] = Field(default_factory=dict)
    env_ok: bool = True
    cameras: list[CameraPlan] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    census: dict[str, Any] = Field(default_factory=dict)


def zone_files(ws: Workspace) -> list[Path]:
    d = ws.src / "zones"
    return sorted(p for p in d.glob("*.js") if not p.name.startswith("_")) if d.is_dir() else []


def glb_assets(ws: Workspace) -> list[str]:
    d = ws.public / "assets"
    return sorted(p.stem for p in d.glob("*.glb")) if d.is_dir() else []


def sun_azimuth(ws: Workspace, default: float = 45.0) -> float:
    env = ws.src / "env.js"
    if env.is_file():
        m = _SUN_RE.search(env.read_text(errors="replace"))
        if m:
            return float(m.group(1))
    return default


# --------------------------------------------------------------------------- probing
def _probe_module(zones: list[Path], glbs: list[str]) -> str:
    entries = ",\n".join(f"    ['{to_snake(p.stem)}', './zones/{p.name}']" for p in zones)
    glb_lines = ", ".join(f"{g}: '/assets/{g}.glb'" for g in glbs)
    return f"""// generated by codeverse assembler — probes env + zone modules independently; deleted after use
import * as THREE from 'three';
const ZONES = [
{entries}
];
export async function createScene({{ renderer, loaders }}) {{
  const scene = new THREE.Scene();
  const ctx = {{ THREE, scene, renderer, loaders, heightAt: () => 0, assets: {{}}, env: {{}} }};
  const assetFiles = {{ {glb_lines} }};
  for (const [k, url] of Object.entries(assetFiles)) {{
    try {{ ctx.assets[k] = (await loaders.gltf.loadAsync(url)).scene; }}
    catch (e) {{ console.error('{_PREFIX} asset ' + k + ' failed: ' + ((e && e.message) || e)); }}
  }}
  let env = null;
  try {{
    const m = await import('./env.js');
    if (typeof m.heightAt === 'function') ctx.heightAt = m.heightAt;
    if (typeof m.buildEnv === 'function') env = await m.buildEnv(ctx);
    ctx.env = env || {{}};
  }} catch (e) {{ console.error('{_PREFIX} env failed: ' + ((e && e.stack) || e)); }}
  const wraps = [];
  for (const [name, rel] of ZONES) {{
    try {{
      const m = await import(rel);
      if (typeof m.build !== 'function') throw new Error('module has no export build(ctx)');
      const g = await m.build(ctx);
      if (!g || !g.isObject3D) throw new Error('build(ctx) did not return a THREE.Object3D');
      const wrap = new THREE.Group();
      wrap.name = '__zone__' + name;
      wrap.add(g);
      scene.add(wrap);
      wraps.push(wrap);
    }} catch (e) {{ console.error('{_PREFIX} zone ' + name + ' failed: ' + ((e && e.stack) || e)); }}
  }}
  return {{
    scene,
    cameras: [{{ name: 'probe', position: [30, 20, 30], lookAt: [0, 0, 0], fov: 50 }}],
    update(t, dt) {{
      try {{ if (env && env.update) env.update(t, dt); }} catch (e) {{ console.error('{_PREFIX} env update failed: ' + e); }}
      for (const w of wraps) {{
        const z = w.children[0];
        try {{ if (z && z.userData.update) z.userData.update(t, dt); }} catch (e) {{ console.error('{_PREFIX} zone ' + w.name.slice(8) + ' update failed: ' + e); }}
      }}
    }},
  }};
}}
"""


def probe_zone_modules(ws: Workspace, *, timeout_s: float = 90.0, sun_azimuth_deg: float | None = None) -> ZoneProbeReport:
    """Probe env + every zone module independently in the browser host.

    Returns a :class:`ZoneProbeReport` (unpacks as the historical 3-tuple of
    zone probes by snake name, census, other console errors).  When
    ``sun_azimuth_deg`` is given the driver also fits overview + per-group
    cameras from the measured bboxes (``camera_specs``).
    """
    from codeverse.spatial.render_scene import run_scene_script

    zones = zone_files(ws)
    probe_path = ws.root / PROBE_REL
    probe_path.write_text(_probe_module(zones, glb_assets(ws)))
    args = ["--ws", str(ws.root), "--scene", PROBE_REL, "--timeout-ms", str(int(timeout_s * 1000))]
    if sun_azimuth_deg is not None:
        args += ["--sun-azimuth", str(sun_azimuth_deg)]
    try:
        res = run_scene_script("probe_scene.mjs", args, timeout_s=timeout_s + 20)
    finally:
        probe_path.unlink(missing_ok=True)
    s = res.summary
    boot = s.get("boot") or {}
    errors: list[str] = list(s.get("console_errors", []))
    if not boot.get("ok"):
        errors.insert(0, f"probe scene did not boot [{boot.get('stage')}]: {boot.get('error', '')}")
    failed: dict[str, str] = {}
    other: list[str] = []
    for e in errors:
        m = re.match(rf"(?:console: )?{re.escape(_PREFIX)} zone (\S+) failed: (.*)", e, re.S)
        if m:
            failed[m.group(1)] = m.group(2).strip()[:600]
        else:
            other.append(e)
    census = s.get("census") or {}
    groups = {g["name"]: g for g in census.get("groups", [])}
    probes: dict[str, ZoneProbe] = {}
    for p in zones:
        name = to_snake(p.stem)
        g = groups.get(f"__zone__{name}")
        if name in failed or g is None:
            probes[name] = ZoneProbe(name=name, file=f"src/zones/{p.name}", ok=False,
                                     error=failed.get(name, "zone not present after probe (build returned nothing visible?)"))
        else:
            probes[name] = ZoneProbe(name=name, file=f"src/zones/{p.name}", ok=True, bbox=g.get("bbox"),
                                     meshes=g.get("meshes", 0), triangles=g.get("triangles", 0))
    return ZoneProbeReport(probes=probes, census=census, other_errors=other, camera_specs=s.get("fitted_cameras") or {})


# --------------------------------------------------------------------------- cameras
_FALLBACK_CAMERA = CameraPlan(name="overview", position=(30.0, 18.0, 30.0), look_at=(0.0, 1.0, 0.0), fov=50.0,
                              purpose="fallback: no measurable zones")


def _plan_from_spec(spec: dict[str, Any], *, name: str, purpose: str) -> CameraPlan:
    return CameraPlan(name=name, position=tuple(spec["position"]), look_at=tuple(spec["lookAt"]),
                      fov=float(spec.get("fov", 50.0)), purpose=purpose)


def cameras_from_specs(specs: dict[str, Any], probes: dict[str, ZoneProbe], *, max_cameras: int = 6) -> list[CameraPlan]:
    """Convert driver-fitted camera specs (``probe_scene.mjs --sun-azimuth``;
    math owned by ``runtime_js/lib/orbit.mjs``) into CameraPlans: overview
    first, then per-zone cameras, largest footprints first.  Falls back to a
    fixed overview when nothing was measurable."""
    healthy = [p for p in probes.values() if p.ok and p.bbox]
    overview = (specs or {}).get("overview")
    if not healthy or not overview:
        return [_FALLBACK_CAMERA.model_copy()]
    cams = [_plan_from_spec(overview, name="overview", purpose="overview fitted to measured content bounds, sun side")]
    by_zone = {str(z.get("group", "")).removeprefix("__zone__"): z for z in (specs or {}).get("zones", [])}
    by_area = sorted(healthy, key=lambda p: -(p.bbox["size"][0] * p.bbox["size"][2]))
    for p in by_area[: max_cameras - 1]:
        spec = by_zone.get(p.name)
        if spec:
            cams.append(_plan_from_spec(spec, name=f"{to_snake(p.name)}_view", purpose=f"zone {to_pascal(p.name)} from the sun side"))
    return cams


# --------------------------------------------------------------------------- scene.js
def _cam_literal(c: CameraPlan) -> str:
    p, la = c.position, c.look_at
    return (f"    {{ name: '{to_snake(c.name)}', position: [{p[0]:g}, {p[1]:g}, {p[2]:g}], "
            f"lookAt: [{la[0]:g}, {la[1]:g}, {la[2]:g}], fov: {c.fov:g} }},")


def render_scene_js(zones: list[str], cameras: list[CameraPlan], glbs: list[str], *, env_ok: bool = True) -> str:
    """Deterministic src/scene.js source for the given healthy zone snake names."""
    imports = "\n".join(f"import {{ build as build{to_pascal(z)} }} from './zones/{z}.js';" for z in zones)
    calls = "\n".join(f"  await addZone(build{to_pascal(z)}, '{to_pascal(z)}');" for z in zones)
    env_import = "import { buildEnv, heightAt } from './env.js';" if env_ok else ""
    # buildEnv/build may be async (lint + the assembler probe both accept it): await consistently
    env_build = "  const env = (await buildEnv(ctx)) || {};\n  ctx.env = env;" if env_ok else "  const env = {};"
    height = "heightAt" if env_ok else "() => 0"
    glb_lines = ", ".join(f"{g}: '/assets/{g}.glb'" for g in glbs)
    cams = "\n".join(_cam_literal(c) for c in cameras)
    return f"""// src/scene.js — ASSEMBLED BY THE HARNESS (codeverse assembler). Edit zones/env instead; re-assembly overwrites this file.
import * as THREE from 'three';
{env_import}
{imports}

export async function createScene({{ renderer, loaders }}) {{
  const scene = new THREE.Scene();
  const ctx = {{ THREE, scene, renderer, loaders, heightAt: {height}, assets: {{}} }};
  const assetFiles = {{ {glb_lines} }};
  for (const [key, url] of Object.entries(assetFiles)) {{
    try {{ ctx.assets[key] = (await loaders.gltf.loadAsync(url)).scene; }}
    catch (e) {{ console.error(`[assets] failed to load ${{url}}: ${{e && e.message}}`); }}
  }}
{env_build}

  const zones = [];
  const addZone = async (build, name) => {{
    const g = await build(ctx);
    if (!g || !g.isObject3D) throw new Error(`zone ${{name}}: build(ctx) must return a THREE.Group`);
    if (!g.name) g.name = name;
    scene.add(g);
    zones.push(g);
  }};
{calls}

  const cameras = [
{cams}
  ];

  function update(t, dt) {{
    if (env.update) env.update(t, dt);
    for (const z of zones) if (z.userData.update) z.userData.update(t, dt);
  }}
  return {{ scene, cameras, update }};
}}
"""


def assemble(ws: Workspace, plan: ScenePlan | None = None, *, cameras: str = "derive", probe: bool = True,
             timeout_s: float = 90.0) -> AssembleResult:
    """Probe zones, derive cameras, write ``src/scene.js``.  ``cameras='plan'`` keeps the plan's."""
    warnings: list[str] = []
    zones = zone_files(ws)
    if not zones:
        raise FileNotFoundError(f"no zone modules under {ws.src / 'zones'}")
    env_ok = (ws.src / "env.js").is_file()
    if not env_ok:
        warnings.append("src/env.js missing: scene assembled without env (flat ground at y=0, no lights unless zones add them)")
    probes: dict[str, ZoneProbe] = {}
    census: dict[str, Any] = {}
    camera_specs: dict[str, Any] = {}
    if probe:
        report = probe_zone_modules(ws, timeout_s=timeout_s, sun_azimuth_deg=sun_azimuth(ws))
        probes, census, camera_specs = report.probes, report.census, report.camera_specs
        for o in report.other_errors:
            if _PREFIX in o and "env failed" in o:
                env_ok = False
                warnings.append(f"env.js failed in probe; assembled without it: {o[:300]}")
            else:
                warnings.append(o[:300])
    else:
        probes = {to_snake(p.stem): ZoneProbe(name=to_snake(p.stem), file=f"src/zones/{p.name}", ok=True) for p in zones}
    healthy = [n for n, p in probes.items() if p.ok]
    failed = {n: p.error for n, p in probes.items() if not p.ok}
    if not healthy:
        warnings.append("no zone module survived probing; scene.js assembled with zero zones")
    if cameras == "plan" and plan is not None and plan.cameras:
        cams = list(plan.cameras[:6])
    else:
        cams = cameras_from_specs(camera_specs, probes)
    text = render_scene_js(healthy, cams, glb_assets(ws), env_ok=env_ok)
    out = ws.src / "scene.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    (ws.artifacts).mkdir(parents=True, exist_ok=True)
    result = AssembleResult(scene_path=str(out), zones_included=healthy, zones_failed=failed, env_ok=env_ok,
                            cameras=cams, warnings=warnings, census=census)
    (ws.artifacts / "assemble.json").write_text(json.dumps(result.model_dump(mode="json"), indent=1))
    return result
